regina keku
rohjay/favorite_movie_quotes pull request #1
Opened 2017-06-08 17:36 UTC by henceagrin36

added a good LOTR quote 👍

2017-06-08 18:35 UTC, rohjay requested changes
One small change and we're good =]

2017-06-08 18:35 UTC, rohjay commented on favorite_movie_quotes.txt
*nitpick* ~ There's some odd whitespace here...

2023-06-27 00:13 UTC, closed without merging

2023-07-20 18:02 UTC, rohjay commented
Heyyyy Regina! You cleanin' up for anything special? 😉

I hope you're well and life is good =]

2023-08-28 23:26 UTC, henceagrin36 commented
hey Ryan, sorry just saw this reply! hope you're doing well too, and that you're the same awesome human being (if not more)!

no real reason for closing this haha. thanks for teaching me about git back in the day – and look! now I can close PRs too!

2023-08-29 13:20 UTC, rohjay commented
Awwww you're gonna make me blush! It was my pleasure - it's great to see you out rockin' in your career. I know it's not my place, and my hand had very little to do with it, but I'm proud of you! You always were a smart cookie =]

Keep on keepin' on, Regina. Reach out if you need anything from an old mentor!